### ISSUE TITLE
需要更新字典信息，有的数据不对

### ISSUE THREAD

**Issue by lhq0826** [medz/id-card-of-china#1]
山西省的数据有问题

**Comment by lhq0826** [comment]
弄错了，原来数据是一直在变化的，`In Region.php line 93:`需要加个报错处理是不是呢？

**Comment by medz** [comment]
好的 我排查下，谢谢

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年7月18日，17:20，lhq0826 <notifications@github.com<mailto:notifications@github.com>> 写道：


山西省的数据有问题

**Comment by medz** [comment]
正在重构地区数据库的包，重构完成就可以获取老数据～就是无论地区如何更新，子 1990 年开始的地区对应的身份证号码的地区都能正确处理。

**Comment by lhq0826** [comment]
👍

**Comment by medz** [comment]
已经重构完成，可以获取历史年份的数据了！
